## Pandas library

### Characteristics of pandas


*   open-source python library
*   for data manipulation and analysis
*   works with structured data
*   two core data structures:
    *   series (1D)
    *   dataframe (2D)

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

data = {
    'Name': ["Player_A", "Player_B", "Player_C"],
    'Age': [25, 30, 35]}

df = pd.DataFrame(data)
print(df)

       Name  Age
0  Player_A   25
1  Player_B   30
2  Player_C   35

In [4]:
# custom indexing

age_series = pd.Series([25, 30, 35], index=["Player_A", "Player_B", "Player_C"])
print(age_series)

Player_A    25
Player_B    30
Player_C    35
dtype: int64



*   CSV files are loaded into dataframe using `read_csv()` function
*   to view all the rows, use `to_string()` or `pd.options.display.max_rows` setting

In [6]:
df1 = pd.read_csv('color.csv')
print(df1)
df1

       Name      HEX               RGB
0     White  #FFFFFF  rgb(100,100,100)
1    Silver  #C0C0C0     rgb(75,75,75)
2      Gray  #808080     rgb(50,50,50)
3     Black  #000000        rgb(0,0,0)
4       Red  #FF0000      rgb(100,0,0)
5    Maroon  #800000       rgb(50,0,0)
6    Yellow  #FFFF00    rgb(100,100,0)
7     Olive  #808000      rgb(50,50,0)
8      Lime  #00FF00      rgb(0,100,0)
9     Green  #008000       rgb(0,50,0)
10     Aqua  #00FFFF    rgb(0,100,100)
11     Teal  #008080      rgb(0,50,50)
12     Blue  #0000FF      rgb(0,0,100)
13     Navy  #000080       rgb(0,0,50)
14  Fuchsia  #FF00FF    rgb(100,0,100)
15   Purple  #800080      rgb(50,0,50)

       Name      HEX               RGB
0     White  #FFFFFF  rgb(100,100,100)
1    Silver  #C0C0C0     rgb(75,75,75)
2      Gray  #808080     rgb(50,50,50)
3     Black  #000000        rgb(0,0,0)
4       Red  #FF0000      rgb(100,0,0)
5    Maroon  #800000       rgb(50,0,0)
6    Yellow  #FFFF00    rgb(100,100,0)
7     Olive  #808000      rgb(50,50,0)
8      Lime  #00FF00      rgb(0,100,0)
9     Green  #008000       rgb(0,50,0)
10     Aqua  #00FFFF    rgb(0,100,100)
11     Teal  #008080      rgb(0,50,50)
12     Blue  #0000FF      rgb(0,0,100)
13     Navy  #000080       rgb(0,0,50)
14  Fuchsia  #FF00FF    rgb(100,0,100)
15   Purple  #800080      rgb(50,0,50)

In [8]:
import json

with open('sample.json') as f:
  data = json.load(f)

df3 = pd.DataFrame([data])
df3

# when json file is in valid format to use with pandas
# df2 = pd.read_json("sample.json")
# df2

   fruit   size color
0  Apple  Large   Red

In [17]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
        'Age': [24, 27, 22, 32, 29],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']}
df4 = pd.DataFrame(data)

print("the dataframe:")
print(df4)

print("\nthe data at the second row")
print(df4.loc[2])

print("\nFirst 2 rows using head():")
print(df4.head(2))

print("\nLast 2 rows using tail():")
print(df4.tail(2))

print("\nDataFrame summary using info():")
df4.info()

print("\nDataFrame summary using describe():")
print(df4.describe(include='all'))
df4.describe()

the dataframe:
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eva   29      Phoenix

the data at the second row
Name    Charlie
Age          22
City    Chicago
Name: 2, dtype: object

First 2 rows using head():
    Name  Age         City
0  Alice   24     New York
1    Bob   27  Los Angeles

Last 2 rows using tail():
    Name  Age     City
3  David   32  Houston
4    Eva   29  Phoenix

DataFrame summary using info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

DataFrame summary using describe():
         Name        Age      City
count       5   5.000000         5
unique      5        NaN         5
top     Alice        NaN  New York
freq        1        NaN         1
mean      NaN  26.800000       NaN
std       NaN   3.962323       NaN
min       NaN  22.000000       NaN
25%       NaN  24.000000       NaN
50%       NaN  27.000000       NaN
75%       NaN  29.000000       NaN
max       NaN  32.000000       NaN

             Age
count   5.000000
mean   26.800000
std     3.962323
min    22.000000
25%    24.000000
50%    27.000000
75%    29.000000
max    32.000000

In [19]:
df4['Name'].describe()

count         5
unique        5
top       Alice
freq          1
Name: Name, dtype: object

In [20]:
percentiles = [.20, .40, .60, .80]
df4['Age'].describe(percentiles = percentiles)

count     5.000000
mean     26.800000
std       3.962323
min      22.000000
20%      23.600000
40%      25.800000
50%      27.000000
60%      27.800000
80%      29.600000
max      32.000000
Name: Age, dtype: float64

In [23]:
import numpy as np

students = [
    ('Ankit', 22, 'Up', 'Geu'),
    ('Ankita', np.nan, 'Delhi', np.nan),
    ('Rahul', 16, 'Tokyo', 'Abes'),
    ('Simran', 41, 'Delhi', 'Gehu'),
    ('Shaurya', np.nan, 'Delhi', 'Geu'),
    ('Shivangi', 35, 'Mumbai', np.nan),
    ('Swapnil', 35, np.nan, 'Geu'),
    (np.nan, 35, 'Uk', 'Geu'),
    ('Jeet', 35, 'Guj', 'Gehu'),
    (np.nan, np.nan, np.nan, np.nan)
]

details = pd.DataFrame(
    students,
    columns=['Name', 'Age', 'Place', 'College'],
    index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'i', 'j', 'k']
)

print("Boolean DataFrame:\n", details.isnull())
print("\nCount of NaN in each column:\n", details.isnull().sum())
print("\nCount total NaN in the DataFrame:\n", details.isnull().sum().sum())

Boolean DataFrame:
     Name    Age  Place  College
a  False  False  False    False
b  False   True  False     True
c  False  False  False    False
d  False  False  False    False
e  False   True  False    False
f  False  False  False     True
g  False  False   True    False
i   True  False  False    False
j  False  False  False    False
k   True   True   True     True

Count of NaN in each column:
 Name       2
Age        3
Place      2
College    3
dtype: int64

Count total NaN in the DataFrame:
 10

In [24]:
print(details.size)
print(details.shape)
print(details.ndim)

40
(10, 4)
2

#### Creating a Dataframe to select rows with max and min values in Dataframe

In [25]:
dictionary = {'Driver': ['Hamilton', 'Vettel', 'Raikkonen',
                    'Verstappen', 'Bottas', 'Ricciardo',
                    'Hulkenberg', 'Perez', 'Magnussen',
                    'Sainz', 'Alonso', 'Ocon', 'Leclerc',
                    'Grosjean', 'Gasly', 'Vandoorne',
                    'Ericsson', 'Stroll', 'Hartley', 'Sirotkin'],

         'Points': [408, 320, 251, 249, 247, 170, 69, 62, 56,
                    53, 50, 49, 39, 37, 29, 12, 9, 6, 4, 1],

         'Age': [33, 31, 39, 21, 29, 29, 31, 28, 26, 24, 37,
                 22, 21, 32, 22, 26, 28, 20, 29, 23]}

# creating dataframe using DataFrame constructor
df5 = pd.DataFrame(dictionary)
print(df5.head(10))

       Driver  Points  Age
0    Hamilton     408   33
1      Vettel     320   31
2   Raikkonen     251   39
3  Verstappen     249   21
4      Bottas     247   29
5   Ricciardo     170   29
6  Hulkenberg      69   31
7       Perez      62   28
8   Magnussen      56   26
9       Sainz      53   24

In [28]:
# Example 1: Shows max on Driver, Points, and Age columns.
print(df5.max())
print()

# Example 2: Who scored max points
print(df5[df5.Points == df5.Points.max()])
print()

# Example 3: What is the maximum age
print(df5.Age.max())
print()

# Example 4: Who is the oldest driver
print(df5[df5.Age == df5.Age.max()])

Driver    Vettel
Points       408
Age           39
dtype: object

     Driver  Points  Age
0  Hamilton     408   33

39

      Driver  Points  Age
2  Raikkonen     251   39

In [29]:
# Example 1: Shows min on Driver, Points, Age columns.
print(df5.min())
print()

# Example 2: Who scored min points
print(df5[df5.Points == df5.Points.min()])
print()

# Example 3: Which row has minimum age in the Dataframe who is the youngest driver
print(df5[df5.Age == df5.Age.min()])

Driver    Alonso
Points         1
Age           20
dtype: object

      Driver  Points  Age
19  Sirotkin       1   23

    Driver  Points  Age
17  Stroll       6   20